name: Build and Release JAR

on:
  push:
    branches:
      - main  # Trigger this workflow only on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      #  Set up Java (ensure the correct Java version is used)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use OpenJDK distribution
          java-version: '17'       # Use the required Java version (or change as needed)

      # Build the JAR file using Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # Upload the JAR file as an artifact
      - name: Upload JAR as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: aes-encryption-tool
          path: build/libs/*.jar

      # Optional Step: Create a GitHub Release and upload the JAR
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0  # Auto-increment this in real pipelines
          release_name: "AES Encryption Utility"
          body: "New release with latest JAR build."
          draft: false
          prerelease: false

      # Upload the JAR file to the release
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/*.jar
          asset_name: aes-encryption-tool.jar
          asset_content_type: application/java-archive
