name: Build and Release JAR

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set execute permissions for gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 3: Set up Java (Ensure the correct Java version)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Adjust if needed

      # Step 4: Build the JAR using Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Debug - List Build Directory
        run: ls -R app/build

      # Step 5: Upload the JAR file as an artifact
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: aes-encryption-tool
          path: app/build/libs/*.jar

      - name: List JAR Files
        run: ls -R app/build/libs

      # Optional: Create GitHub release and upload the JAR
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0-${{ github.run_id }}
          name: "AES Encryption Utility"
          body: "New release with the latest JAR build."
          draft: false
          prerelease: false
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/libs/aes-encryption-tool.jar
          asset_name: aes-encryption-tool.jar
          asset_content_type: application/java-archive
        env:
         GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
